services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  motimate:
    build:
      context: .            # project root where Dockerfile is
      dockerfile: Dockerfile
    container_name: motimate
    depends_on:
      - ollama
    env_file: src/.env      # because your .env is inside src/
    environment:
      OLLAMA_HOST: http://ollama:11434
      INSTA_SETTINGS_PATH: /app/data/insta_settings.json
      RUN_TIME: "17:00"        # container local time (IST if TZ=Asia/Kolkata)
      RUN_CMD: "python src/main.py"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    restart: "no"

volumes:
  ollama_data: